### ISSUE TITLE
Dependency issue with a site

### ISSUE THREAD

**Issue by nyue** [ebi-gene-expression-group/atlas#160]
Hi,

  Attempting to build a git clone of this software and got the following (on both the dev and master branch)

  [ERROR] Failed to execute goal on project atlas-base: Could not resolve dependencies for project uk.ac.ebi.atlas:atlas-base:jar:5.0: Failed to collect dependencies at uk.ac.ebi.fg:ae-efo-loader:jar:1.0.5: Failed to read artifact descriptor for uk.ac.ebi.fg:ae-efo-loader:jar:1.0.5: Could not transfer artifact uk.ac.ebi.fg:ae-efo-loader:pom:1.0.5 from/to artifactory-repo (http://bar.ebi.ac.uk:8081/artifactory/repo/): bar.ebi.ac.uk: Name or service not known: Unknown host bar.ebi.ac.uk: Name or service not known -> [Help 1]

  Is the site just temporary having problems ? Is there a work around ?

Cheers

**Comment by alfonsomunozpomer** [comment]
Hi Nicholas,

There’s this artifact, `ae-efo-loader`, which is hosted in [EBI’s internal Artifactory repository](https://github.com/ebi-gene-expression-group/atlas/blob/dev/base/pom.xml#L70).

I’ve uplodaded the package here: https://send.firefox.com/download/8f22eb61d8/#Txbzk2iKdTZMXCffWY5faQ

Download it and [install it as a local Maven package[(https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html).

HTH

**Comment by nyue** [comment]
The download link has expired. Is there a more permanent place to retrieve them from ?

**Comment by alfonsomunozpomer** [comment]
Sorry for the long delay in the reply! I was abroad for a few weeks, plus work, etc.

I placed the dependency in this permanent URL:
https://www.ebi.ac.uk/~amunoz/ae-efo-loader-1.0.5.tgz

It’s packaged to be unarchived straight into your local Maven repository. Please, let me know how that goes.

We’re almost finished with a few repositories with all the test data necessary to run an Expression Atlas instance. Among these there’s a containerized Solr and Postgres database with a few experiments already loaded with all the necessary data files. If you’re interested (and willing to wait a week or so), please let me know and I can keep you updated.

**Comment by nyue** [comment]
Yes I am interested, keep me posted.

**Comment by alfonsomunozpomer** [comment]
We’re archiving this repository as it has been superseded by [the library Expression Atlas Core](https://github.com/ebi-gene-expression-group/atlas-web-core) and the web applications of [bulk Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-bulk) and [Single Cell Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-single-cell).

Please, follow the repositories of [bulk Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-bulk) and [Single Cell Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-single-cell) and open any issues there if you’re still interested in building any of the two flavours of Expression Atlas in your environment.

Sorry for the hassle!
